"""
\U0001F4BE
Init
\U0001F4BE
An enterprise is composed of:
\n\t    \U0001F489 CEO  \n
\n\t    \U0001F57A Team leader \n
\n\t    \U0001F3C2 Scrum master \n
\n\t    \U0001F469 Several employees \n
At the beginning, the CEO will create the enterprise giving his guidelines to team leader and scrum master.\n
Each employee will be hired by the team leader for their skills. \n
An employee is defined as a system prompt, automatically generated by the team leader, that describe his skills.\n
The scrum master will then create a sequence of tasks, each associated to an employee previously hired by the team leader.\n
At the end, all tasks result will be returned to the CEO.\n
"""

from .__main__ import main
